InformationalApplication/InformationalApplication/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace InformationalApplication.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            return View();
        }
    }
}

InformationalApplication/InformationalApplication/Controllers/SiteContentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace InformationalApplication.Controllers
{
    public class SiteContentController : Controller
    {

        public ActionResult ReturnPartialView(string pageName)
        {
            return PartialView(pageName);
        }

	}
}

InformationalApplication/InformationalApplication/Views/Shared/_Layout - Copy.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
        @Styles.Render("~/Content/style.css")
</head>
<body>
    <nav>
        <ul>
            <li class="nav-item"><h4>Съдържание</h4></li>
            <li class="nav-item"><h4>@Html.ActionLink("Обща информация за стрес тестването","Overview","SiteContent")</h4></li>
            <li class="nav-item"><h4>@Html.ActionLink("Примери за стрес условия", "StressConditionsExample", "SiteContent")</h4></li>
            <li class="nav-item"><h4>@Html.ActionLink("Примери за симптоми, свързани със Стрес", "StressConditionsExample", "SiteContent")</h4></li>
            <li class="nav-item"><h4>@Html.ActionLink("Как да използваме информацията дадена тук", "StressConditionsExample", "SiteContent")</h4></li>
            <li class="nav-item"><h4>@Html.ActionLink("Input", "StressConditionsExample", "SiteContent")</h4></li>
            <li class="nav-item"><h4>@Html.ActionLink("Output", "StressConditionsExample", "SiteContent")</h4></li>
            <li class="has-sub nav-item">
                <h4>@Html.ActionLink("Подход към Стрес тестване >", "StressConditionsExample", "SiteContent")</h4>
                <ul class="sub-menu">

                    <li class="nav-item">
                        <h4>@Html.ActionLink("Стъпка 1 - Определяне на целите на стрес-тестването.", "StressConditionsExample", "SiteContent")</h4>
                    </li>

                    <li class="nav-item">
                        <h4>@Html.ActionLink("Стъпка 2 - Определяне на ключов/и сценарий/сценарии.", "StressConditionsExample", "SiteContent")</h4>
                    </li>

                    <li class="nav-item">
                        <h4>@Html.ActionLink("Стъпка 3 – Определяне на натоварване.", "StressConditionsExample", "SiteContent")</h4>
                    </li>

                    <li class="nav-item">
                        <h4>@Html.ActionLink("Стъпка 4 – Определяне на показателите.", "StressConditionsExample", "SiteContent")</h4>
                    </li>

                    <li class="nav-item">
                        <h4>@Html.ActionLink("Стъпка 5 – Създаване на случаи за тестване.", "StressConditionsExample", "SiteContent")</h4>
                    </li>

                    <li class="nav-item">
                        <h4>@Html.ActionLink("Стъпка 6 – Симулиране на натоварване.", "StressConditionsExample", "SiteContent")</h4>
                    </li>

                    <li class="nav-item">
                        <h4>@Html.ActionLink("Стъпка 7 – Анализиране на резултатите.", "StressConditionsExample", "SiteContent")</h4>
                    </li>

                </ul>
            </li>
            <li class="nav-item"><h4>@Html.ActionLink("Сценарии за Стрес-Тестване", "StressConditionsExample", "SiteContent")</h4></li>
            <li class="nav-item"><h4>@Html.ActionLink("Проучвателно стрес-тестване", "StressConditionsExample", "SiteContent")</h4></li>
            <li class="nav-item"><h4>@Html.ActionLink("Някои инструменти за стрес-тестване:", "StressConditionsExample", "SiteContent")</h4></li>
            <li class="nav-item"><h4>@Html.ActionLink("Заключение", "StressConditionsExample", "SiteContent")</h4></li>
            <li class="nav-item"><h4>@Html.ActionLink("Референции:", "StressConditionsExample", "SiteContent")</h4></li>
        </ul>

    </nav>
    <div class="container body-content">
        @RenderBody()
    </div>
    <script src="~/Scripts/jquery-2.1.1.min.js"></script>
    @Scripts.Render("~/Scripts/jquery-2.1.1.min.js")
    @Scripts.Render("~/Scripts/script.js")
</body>
</html>

InformationalApplication/InformationalApplication/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
        @Styles.Render("~/Content/style.css")
</head>
<body>
    <nav>
        <ul>
            <li class="nav-item"><h4>Съдържание</h4></li>
            <li class="nav-item"><h4 id="1" value="_Overview">Обща информация за стрес тестването</h4></li>
            <li class="nav-item"><h4 id="2" value="_StressConditionsExamples">Примери за стрес условия</h4></li>
            <li class="nav-item"><h4 id="3" value="_StressRelatedSymptomsExamples">Примери за симптоми, свързани със Стрес</h4></li>
            <li class="nav-item"><h4 id="4" value="_HowToUseTheGivenInformarion">Как да използваме информацията дадена тук</h4></li>
            <li class="nav-item"><h4 id="5" value="_Input">Input</h4></li>
            <li class="nav-item"><h4 id="6" value="_Output">Output</h4></li>
            <li class="has-sub nav-item">
                <h4 id="7" value="_StressTestingApproach">Подход към Стрес тестване ></h4>
                <ul class="sub-menu">

                    <li class="nav-item">
                        <h4 id="8" value="_S1_IdentifyTestObjectives">Стъпка 1 - Определяне на целите на стрес-тестването.</h4>
                    </li>

                    <li class="nav-item">
                        <h4 id="9" value="_S2_IdentifyKeyScenarios">Стъпка 2 - Определяне на ключов/и сценарий/сценарии.</h4>
                    </li>

                    <li class="nav-item">
                        <h4 id="10" value="_S3_IdentifyWorkload">Стъпка 3 – Определяне на натоварване.</h4>
                    </li>

                    <li class="nav-item">
                        <h4 id="11" value="_S4_IdentifyMetrics">Стъпка 4 – Определяне на показателите.</h4>
                    </li>

                    <li class="nav-item">
                        <h4 id="12" value="_S5_CreateTestCases">Стъпка 5 – Създаване на случаи за тестване.</h4>
                    </li>

                    <li class="nav-item">
                        <h4 id="13" value="_S6_SimulateLoad">Стъпка 6 – Симулиране на натоварване.</h4>
                    </li>

                    <li class="nav-item">
                        <h4 id="14" value="_S7_AnalyzeResults">Стъпка 7 – Анализиране на резултатите.</h4>
                    </li>

                </ul>
            </li>
            <li class="nav-item"><h4 id="15" value="_StressTestingUsageScenarios">Сценарии за Стрес-Тестване</h4></li>
            <li class="nav-item"><h4 id="16" value="_ExploratoryStressTesting">Проучвателно стрес-тестване</h4></li>
            <li class="nav-item"><h4 id="17" value="_SomeStressTestTools">Някои инструменти за стрес-тестване:</h4></li>
            <li class="nav-item"><h4 id="18" value="_Summary">Заключение</h4></li>
            <li class="nav-item"><h4 id="19" value="_Referenses">Референции:</h4></li>
            
        </ul>

    </nav>
    <div class="body-text">

        <div class="container body-content">
            @RenderBody()
        </div>
    </div>
        @Scripts.Render("~/Scripts/jquery-2.1.1.min.js")
        @Scripts.Render("~/Scripts/script.js")

</body>
</html>

InformationalApplication/InformationalApplication/Views/SiteContent/_ExploratoryStressTesting.cshtml
<div class="subbody-one">

    <h2><b>Проучвателно стрес-тестване</b></h2>
    <p>Проучвателното стрес-тестване е подход за подчиняване на система. Приложение или компонент на набор от необичайни параметри или условия които са малко вероятни да се появят в реалния свят но все пак са възможни. Като цяло проучвателното тестване може да бъде разглеждано като единен процес на учене, дизайн на тестването и изпълняване на тестването. Най-често този вид стрес-тестове се проектират чрез промяна на вече съществуващи тестове и/или работа с администратори на приложението/системата за да се създадат малко вероятни но възможни условия в системата. Този тип стрес тестване се провежда рядко в изолация защото обикновено се прави с цел да се определи дали повече системни стрес-тестове са нужни за свързан с определена грешка режим. Следните са няколко примера за проучвателно стрес тестване за да се определи отговора на въпроса „Как ще реагира системата ако…?“</p>
    <ul>
        <li>Всички потребители се логват по едно и също време.</li>
        <li>Разпределителя на работа (load balancer) изведнъж се чупи.</li>
        <li>Всички сървъри започват сканиране за вируси по едно и също време докато са в пиков момент на натовареност.</li>
        <li>Базата данни се изключи по време на пикова употреба на системата.</li>
    </ul>
    @Html.ActionLink("Начало", "Index", "Home")
</div>

InformationalApplication/InformationalApplication/Views/SiteContent/_HowToUseTheGivenInformarion.cshtml
<div class="subbody-one">

    <h2><b>Как да използваме информацията дадена тук</b></h2>
    <p>Използвайте информацията дадена тук за да разберете основните похвати на стрес тестването и стъпките които се прилагат при стрес тестването на уеб приложение. За да схванете възможно най-добре нещата:</p>
    <ul>
        <li>Използвайте секциите “Input” и “Output”, за да разберете ключовите входове и изходи при този вид тестване.</li>
        <li>Използвайте секцията “Подход към Стрес-тестване”, за да разберете с какъв подход да тествате уеб приложение, и като бърза справка за вас и вашия екип</li>
        <li>Използвайте секцията “Различни стъпки”, за да разберете подробностите на всяка стъпка при стрес тестването на уеб приложение.</li>
        <li>Използвайте секцията “Сценарии за Стрес-тестване”, за да разберете различни реални сценарии, при които се прилага стрес тестване.</li>
    </ul>
    @Html.ActionLink("Начало", "Index", "Home")
</div>

InformationalApplication/InformationalApplication/Views/SiteContent/_Input.cshtml
<div class="subbody-one">

    <h2><b>Input</b></h2>
    <p>За да приложите стрес-тестване, по-добре използвайте като справка едно от следните неща:</p>
    <ul>
        <li>Резултати от предишни стрес-тестове</li>
        <li>Характеристики за използване на приложение (сценарии)</li>
        <li>Работа при тези сценарии при екстремни условия</li>
        <li>Характеристики при профилно натоварване</li>
        <li>Текущ пиков капацитет на натоварване</li>
        <li>Архитектура и информация за хардуер и мрежа</li>
        <li>Оценка на риска при бедствия</li>
    </ul>
    @Html.ActionLink("Начало", "Index", "Home")


</div>

InformationalApplication/InformationalApplication/Views/SiteContent/_Referenses.cshtml
<div class="subbody-one">

    <h2><b>Референции:</b></h2>
    <ul>
        <li><a href="http://msdn.microsoft.com/en-us/library/bb924374.aspx">http://msdn.microsoft.com/en-us/library/bb924374.aspx</a></li>
        <li><a href="http://docs.seleniumhq.org">http://docs.seleniumhq.org</a></li>
        <li><a href="http://tsung.erlang-projects.org">http://tsung.erlang-projects.org</a></li>
        <li><a href="http://jmeter.apache.org">http://jmeter.apache.org</a></li>
        <li><a href="http://www.webresourcesdepot.com/15-free-functionality-and-load-testing-tools-for-web-applications/">http://www.webresourcesdepot.com/15-free-functionality-and-load-testing-tools-for-web-applications/</a></li>
    </ul>
    @Html.ActionLink("Начало", "Index", "Home")


</div>

InformationalApplication/InformationalApplication/Views/SiteContent/_S2_IdentifyKeyScenarios.cshtml
<div class="subbody-one">

    <h2><b>Стъпка 2 - Определяне на ключов/и сценарий/сценарии.</b></h2>
    <p>За да се получат най-важните резултати от един стрес-тест, той трябва да се фокусира върху сценария или сценариите за употреба които са най важни за цялостния успех на приложението. За да се определят тези сценарии, се започва с определянето първоначално на един сценарий при който искаме да приложим стрес-тестването, с цел да определим потенциалните проблеми при изпълнението на приложението. Вземете в предвид следните неща при избор на сценарий:</p>
    <ul>
        <li>Избирайте сценарии основани на това колко важни са за цялостното изпълнение на приложението.</li>
        <li>Опитайте се да тествате онези операции, които е най-вероятно да влияят на производителността. Те може да включват операции, които правят интензивно заключване и синхронизация, дълги </li>
        <li>Базирайте своя избор на сценарий на специфични части на вашето приложение определени като трафик места от данните за тестване на натоварването. Въпреки че би трябвало да сте настроили фино и да сте премахнали тези места след теста за натоварване, по-добре направете стрес-тест на системата в тези части, за да определите колко добре се справят промените ви при високи нива на стрес.</li>
    </ul>
    <p>Примери за сценарии които да се тестват отделно от други сценарии за употреба за типично приложение за електронна търговия включват следното:</p>
    <ul>
        <li>Сценарий за ъпдейтване на инвентара при обработка на поръчка за определен продукт. Тази функционалност има потенциала да покаже заключващи проблеми и проблеми със синхронизацията.</li>
        <li>Сценарий за показване на резултат, базиран на потребителска заявка. Ако потребителят подаде често заявка с широк обхват, може да има проблем при ползването на паметта. Например използването на паметта може да се засегне от заявка при връщане на цяла таблица от данни.</li>
    </ul>
    @Html.ActionLink("Начало", "Index", "Home")


</div>

InformationalApplication/InformationalApplication/Views/SiteContent/_S3_IdentifyWorkload.cshtml
<div class="subbody-one">

    <h2><b>Стъпка 3 – Определяне на натоварване. </b></h2>
    <p>Натоварването, което прилагате при определен сценарий би трябвало да стресира системата отвъд праговите граници за да ви позволи да наблюдавате последиците от условията на стрес. Един от методите да се определи това натоварване, при което приложението започва да показва признаци на стрес е постепенно да се увеличава натоварването и да се наблюдава поведението на приложението при различните степени на натоварване. Целта е систематично да се тества при различни натоварвания докато не се стигне до крашване или значима грешка. Тези вариации на натовареност могат да се постигнат чрез добавяне на още потребители, намаление на времето за забавяне, добавяне или намаляне на броя и типа на представените дейности на потребителите или настройване на информацията за тестване.</p>
    <p>Например, стрес-теста може да бъде измислен така че да симулира логване на всеки регистриран потребител да се опитва да се логне в системата за период от 30 секунди. Това ще симулира ситуация при която приложението става налично отново след период на изключване и всички потребители са рефрешвали своя уеб браузър, чакайки приложението да стане достъпно. Въпреки че тази ситуация не се появява често в реалния свят, става достатъчно често за да има смисъл от това да разберем как приложението ще работи ако се случи.</p>
    <p>Не забравяйте да представите натоварването чрез точни и реалистични данни – тип и обем, логване на различни потребители, ID-та на продукти, категории на продукти и така нататък – което ни позволява да симулираме важни проблеми като безизходици или употреба на ресурси.</p>
    <p>Следните дейности са полезни за определянето на точно натоварване за стрес тестване:</p>
    <ul>
        <li><b>Определяне на разпределението на работата.</b></li>
        <p>За всеки ключов сценарий, определете разпределението на работата което ще се симулира. Разпределението се основава на броя и типа на потребители, които ще изпълняват сценария по време на стрес тестване.</p>
        <li><b>Определете пиковото натоварване от потребители. </b></li>
        <p>Определете максимума на потребителите които се очакват да използват системата при условия за пиково натоварване на системата. Използвайки разпределението на работата за всеки сценарий, изчислете процента потребители за всеки ключов сценарий.</p>
        <li><b>Определете anti-profile. </b></li>
        <p>Като алтернатива може да започнете като приложите анти-профил към нормалното натоварване. При анти-профила процентите на разпределението на работа са обърнати спрямо сценария на прилагане. Например ако нормалното натоварване за сценарий на процес на поръчка е 10 процента от целия капацитет то при анти-профила ще бъде 90 процента. Останалото натоварване може да бъде разпределено сред другите сценарии. Използването на анти-профил може да послужи като важна начална точка за нашето стрес тестване, защото то осигурява това че критичните сценарии се прилагат при товар отвъд нормалните условия на натоварване.</p>
    </ul>
    @Html.ActionLink("Начало", "Index", "Home")


</div>

InformationalApplication/InformationalApplication/Views/SiteContent/_S5_CreateTestCases.cshtml
<div class="subbody-one">

    <h2><b>Стъпка 5 – Създаване на случаи за тестване. </b></h2>
    <p>Определянето на натоварването и ключовите сценарии не винаги осигурява цялата информация нужна ни за да имплементираме и създадем тестовите случаи. Допълнителни входни данни за цялостно създаване на стрес-тест включват цели за производителност, характеристики за натовареност, тестова информация, тестова среда и определени показатели. Всеки дизайн за тест би трябвало да съдържа очакваните резултати и/или ключовата информация, която да се вземе от него, по такъв начин че всеки сценарий на тест да може да се отбележи като успешен, неуспешен или неопределен след тестване.</p>
    <p>Следното е пример на сценарий за тестване базиран на сценарий за даване на поръчка.</p>
    <h2><b>Тест 1 – Сценарий за даване на поръчка</b></h2>
    <ul>
        <li><b>Натовареност: </b>1000 потребителя по едно и също време.</li>
        <li><b>Време за изпълнение(Think time): </b>Използва се произволно време между 1 и 10 секунди в тестовия скрипт след всяка операция.</li>
        <li><b>Продължителност на теста: </b>Направи теста за два дни.</li>
    </ul>
    <h2><b>Очаквани резултати:</b></h2>
    <ul>
        <li>Процеса на хостване при приложенията не би трябвало да рециклира ресурси заради затруднения или изхабяване на памет.</li>
        <li>Пропусквателността не трябва да пада под 35 заявки за секунда.</li>
        <li>Времето за отговор не трябва да е повече от 7 секунди да 95 процента от всички завършени транзакции.</li>
        <li>Грешките от тип „Зает сървър“ не трябва да са повече от 10 процента от всички отговори.</li>
        <li>Транзакциите за покупки не бива да се провалят по време на изпълнение на тестовете. Входните данни на базата данни трябва да отговарят по бройка на „Успелите транзакции“.</li>
    </ul>
    @Html.ActionLink("Начало", "Index", "Home")


</div>

InformationalApplication/InformationalApplication/Views/SiteContent/_S6_SimulateLoad.cshtml
<div class="subbody-one">

    <h2><b>Стъпка 6 – Симулиране на натоварване. </b></h2>
    <p>След като сте направили предишните стъпки до приемливо ниво, трябва да сте готови да симулирате натоварването което се поражда от стрес тестването. Типично, изпълнението на теста включва следните стъпки:</p>
    <ol>
        <li>Убедете се/Валидирайте че средата за тестване отговаря на конфигурациите, които сте очаквали и/или за които сте проектирали своя тест.</li>
        <li>Гарантирайте, че и теста и средата за тестване са правилно конфигурирани според показателите.</li>
        <li>Преди да проведете теста изпълнете бърз “smoke test” за да сте сигурни че тестовия скрипт и отдалечените системи за следене на производителността работят правилно.</li>
        <li>Рестартирайте системата (Освен ако сценарият казва да се направи обратното) и започнете официалното тестване на приложението.</li>
    </ol>
    <p><b>Бележка:</b> Убедете се, че клиентският компютър който използвате за да генерирате натоварването не е стресиран. Използването на ресурси като процесор и памет трябва да останат достатъчно ниски за да се подсигури че генератора на товар не е затруднен.</p>
    @Html.ActionLink("Начало", "Index", "Home")


</div>

InformationalApplication/InformationalApplication/Views/SiteContent/_S7_AnalyzeResults.cshtml
<div class="subbody-one">

    <h2><b>Стъпка 7 – Анализиране на резултатите. </b></h2>
    <p>Анализирайте данните получени от тестването и ги сравнете с допустимото ниво на показателите. Ако резултатите определят че вашите изисквания за производителност не са покрити, анализирайте и оправете причината за проблема. За да се адресират прегледаните проблеми, може да има нужда да се направи едно от следните неща:</p>
    <ul>
        <li>Направете преглед на дизайна.</li>
        <li>Направете преглед на кода.</li>
        <li>Направете стрес-тестове в среди където е възможно да се дебъгват възможните причини за грешките по време на изпълнение на теста.</li>
    </ul>
    <p>В ситуации, където се наблюдават проблеми с производителността, но само при условия които се считат за малко вероятни да гарантират промяна в момента, може да решите да направите допълнителни тестове за да откриете ранни индикатори за проблем и да предотвратите нежелани изненади.</p>
    @Html.ActionLink("Начало", "Index", "Home")


</div>

InformationalApplication/InformationalApplication/Views/SiteContent/_SomeStressTestTools.cshtml
<div class="subbody-one">

    <h2><b>Някои инструменти за стрес-тестване:</b></h2>
    <ul>
        <li><b>Apache JMeter™</b></li>
        <img src="~/Content/images/52_02.jpg">
        <ol>
            <li>Способност на тества натоварването и производителността на много различни типове сървъри/протоколи:</li>
            <ul>
                <li>Web - HTTP, HTTPS</li>
                <li>SOAP</li>
                <li>FTP</li>
                <li>База данни през JDBC</li>
                <li>LDAP</li>
                <li>Message-oriented middleware (MOM) през JMS</li>
                <li>Mail - SMTP(S), POP3(S) and IMAP(S)</li>
                <li>MongoDB (NoSQL)</li>
                <li>Native commands or shell scripts</li>
                <li>TCP</li>
            </ul>
            <li>Пълна портативност и 100% чиста Java.</li>
            <li>GUI дизайна позволява по бързо планиране на тестови план и дебъгване.</li>
            <li>Кеширане и офлайн анализиране/инициализиране на тест резултатите.</li>
            <li>Високо разширяемо ядро.</li>
        </ol>


        <br>


        <li><b>Selenium</b></li>
        <img src="~/Content/images/52_03.jpg">
        <p>Selenium има различни проекти, които могат да се комбинират и да се създаде среда за тестване на здравина.</p>
        <ul>
            <li><b>Selenium IDE: </b>ад-он за Firefox за записване и пускане не тестове.</li>
            <li><b>Selenium Remote Control: </b>Система клиент/сървър за управление на уеб браузъри локално или други компютри, използвайки почти всеки програмен език и тестващ framework.</li>
            <li><b>Selenium Grid: </b>като selenium Remote Control, но прави тестове на много сървъри по едно и също време.</li>
            <li><b>Selenium Core: </b>Тестваща система базирана на Javascript.</li>
        </ul>


        <br>


        <li><b>Tsung</b></li>
        <img src="~/Content/images/52_04.gif">
        <p>Tsung може да се използва за стрес-тестване на почти всякакви сървъри включително:</p>
        <ul>
            <li>HTTP</li>
            <li>WebDAV</li>
            <li>SOAP</li>
            <li>PostgreSQL, MySQL</li>
            <li>Jabber/XMPP Сървъри</li>
            <li>LDAP</li>
        </ul>
    </ul>
    @Html.ActionLink("Начало", "Index", "Home")


</div>

InformationalApplication/InformationalApplication/Views/SiteContent/_StressConditionsExamples.cshtml
<div class="subbody-one">

    <h2><b>Примери за стрес условия</b></h2>
    <p>Примерите за стрес условия включват:</p>
    <ul>
        <li>Огромен обем от гледна точка или на потребителите или на информацията; примерите могат да включват отказ от услуга (denial of service), атаки или ситуация, където към много популярни новини, например страница за тях, са отправени много заявки за преглед в период от три минути.</li>
        <li>Ограничение на ресурсите, породено например от отказване на дисковото устройство или мястото на което са записани те.</li>
        <li>Неочаквано зацикляне.</li>
        <li>Неочаквано завиване по време на възстановяването.</li>
    </ul>
    @Html.ActionLink("Начало", "Index", "Home")


</div>

InformationalApplication/InformationalApplication/Views/SiteContent/_StressRelatedSymptomsExamples.cshtml
<div class="subbody-one">

    <h2><b>Примери за симптоми, свързани със Стрес</b></h2>
    <p>Симптомите свързани със Стрес включват:</p>
    <ul>
        <li>Данните са загубени или повредени.</li>
        <li>Използването на ресурсите остава неприемливо след като стреса е премахнат.</li>
        <li>Компонентите на приложението отказват при отговор.</li>
        <li>Необработени изключения се представят на потребителя.</li>
    </ul>
    @Html.ActionLink("Начало", "Index", "Home")


</div>

InformationalApplication/InformationalApplication/Views/SiteContent/_StressTestingApproach.cshtml
<div class="subbody-one">

    <h2><b>Подход към Стрес тестване</b></h2>
    <p>Следните стъпки са свързани със стрес-тестването на уеб приложение:</p>
    <ol>
        <li><b>Стъпка 1 – Определяне на целите на стрес-тестването. </b></li>
        <p>Определяне на целите на стрес-тестването спрямо желания резултат от процеса.</p>
        <li><b>Стъпка 2 – Определяне на ключов/и сценарий/сценарии. </b></li>
        <p>Определяне на сценарии или случаи за приложението, за които да се направи стрес-тестване, за да се открие потенциален проблем.</p>
        <li><b>Стъпка 3 – Определяне на натоварване. </b></li>
        <p>Определяне на натовареността, която тестващия иска да приложи при сценариите, определени в предната стъпка. Основава се на натовареността и пиковият капацитет на натоварване.</p>
        <li><b>Стъпка 4 – Определяне на показателите. </b></li>
        <p>Определят се показателите, които искаме да съберем от работата на приложението. После се разглеждат спрямо резултатите и потенциалните проблеми определени в стъпката за определяне на целите на стрес тестването.</p>
        <li><b>Стъпка 5 – Създаване на случаи за тестване. </b></li>
        <p>Създават се тестови случаи в които се определят стъпките за провеждане на един тест, както и очакваните резултати.</p>
        <li><b>Стъпка 6 – Симулиране на натоварване. </b></li>
        <p>Използват се инструменти за тестване, които да симулират нужната натовареност за всеки тестови случай и да вземе резултатите за показателите.</p>
        <li><b>Стъпка 7 – Анализиране на резултатите. </b></li>
        <p>Анализират се показателите взети по време на тестването.</p>
    </ol>
    <p>Тези стъпки са графично изобразени отдолу. Следващата секция обяснява всяка от тези стъпки подробно.</p>
    <figure>

        <img src="~/Content/images/52_02.jpg" />
        <figcaption><b>Фигура 1</b> Стъпки при стрес-тестване</figcaption>
    </figure>
    @Html.ActionLink("Начало", "Index", "Home")


</div>

InformationalApplication/InformationalApplication/Views/SiteContent/_Summary.cshtml
<div class="subbody-one">
    <h2><b>Заключение</b></h2>

    <p>Стрес тестването ни позволява да определим потенциални грешки или проблеми на приложението които се появяват само при екстремни условия. Такива условия варират от изтощение на системните ресурси като памет, процесор, мрежа и капацитет на диска до огромно натоварване в следствие на непредвидими начини на употреба, присъщи за уеб приложенията. Стрес-тестването се центрира около цели и ключови сценарии със наблягане върху здравината, надеждността и стабилността на приложението. Ефективността на стрес-тестването зависи от прилагането на правилната методология и способността правилно да се анализират резултатите от тестването. Прилагането на правилната методология зависи от капацитета за възпроизвеждане на условия за натовареност както за потребителската работа така и за обема на информацията, възпроизвеждането на ключови сценарии и интерпретирането на ключовите показатели за производителност.</p>
    @Html.ActionLink("Начало", "Index", "Home")


</div>